In [1]:
import numpy as np

In [ ]:
l = [1,2,3,4,5]
arr = np.array(l)
print(arr) 

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5], dtype=float)

In [5]:
a

array([1., 2., 3., 4., 5.])

# check dim

In [8]:
a.ndim

1

In [9]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
c.ndim

2

In [12]:
d = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(d)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [13]:
d.ndim

4

# accessing

In [14]:
a

array([1., 2., 3., 4., 5.])

In [15]:
a[2]

np.float64(3.0)

In [19]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#access the value of 3
c[0][2]

np.int64(3)

In [22]:
d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [27]:
#access the value of 5
d[0][0][1][1]

np.int64(5)

In [32]:
#access the value of 8
d[0][0][2][1]

np.int64(8)