In [1]:
import numpy as np

In [ ]:
l = [1,2,3,4,5]
arr = np.array(l)
print(arr) 

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5], dtype=float)

In [5]:
a

array([1., 2., 3., 4., 5.])

# check dim

In [8]:
a.ndim

1

In [9]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
c.ndim

2

In [12]:
d = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(d)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [13]:
d.ndim

4

# accessing

In [14]:
a

array([1., 2., 3., 4., 5.])

In [15]:
a[2]

np.float64(3.0)

In [19]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#access the value of 3
c[0][2]

np.int64(3)

In [22]:
d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [27]:
#access the value of 5
d[0][0][1][1]

np.int64(5)

In [32]:
#access the value of 8
d[0][0][2][1]

np.int64(8)

# row column check

In [36]:
a

array([1., 2., 3., 4., 5.])

In [33]:
a.shape

(5,)

In [37]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
c.shape

(3, 3)

In [38]:
d

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [35]:
d.shape

(1, 1, 3, 3)

In [39]:
a.dtype

dtype('float64')

In [40]:
c.dtype

dtype('int64')

In [41]:
d.dtype

dtype('int64')

# Accessing/changing specific elements, row & column etc

In [42]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# 3 = 500
a[0][2] = 500

In [46]:
a

array([[  1,   2, 500,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14]])

# Zeros/Ones method in numpy

In [48]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
zero.dtype

dtype('float64')

In [51]:
one = np.ones((4,5), dtype=int)
one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
full = np.full((3,4), 60, dtype=float)
full

array([[60., 60., 60., 60.],
       [60., 60., 60., 60.],
       [60., 60., 60., 60.]])