In [1]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

In [2]:
model = ResNet50(weights='imagenet')

102967424/102967424 ━━━━━━━━━━━━━━━━━━━━ 6s 0us/step


# Dog image

In [5]:
img_path = '/content/dog.jfif'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [6]:
x

array([[[[-99.939   , -76.779   , -89.68    ],
         [-99.939   , -76.779   , -89.68    ],
         [-98.939   , -75.779   , -88.68    ],
         ...,
         [-93.939   , -79.779   , -90.68    ],
         [-93.939   , -79.779   , -90.68    ],
         [-93.939   , -79.779   , -90.68    ]],

        [[-99.939   , -76.779   , -89.68    ],
         [-99.939   , -76.779   , -89.68    ],
         [-98.939   , -75.779   , -88.68    ],
         ...,
         [-93.939   , -79.779   , -90.68    ],
         [-93.939   , -79.779   , -90.68    ],
         [-93.939   , -79.779   , -90.68    ]],

        [[-99.939   , -76.779   , -89.68    ],
         [-99.939   , -76.779   , -89.68    ],
         [-98.939   , -75.779   , -88.68    ],
         ...,
         [-94.939   , -80.779   , -91.68    ],
         [-94.939   , -80.779   , -91.68    ],
         [-94.939   , -80.779   , -91.68    ]],

        ...,

        [[-29.939003,  38.221   ,  34.32    ],
         [-29.939003,  40.221   ,  35.32    ]

In [7]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step
35363/35363 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
Predicted: [('n02089973', 'English_foxhound', np.float32(0.60643846)), ('n02088364', 'beagle', np.float32(0.11901983)), ('n02107908', 'Appenzeller', np.float32(0.08893753))]


# Cat image

In [8]:
img_path = '/content/cat.jfif'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [9]:
x

array([[[[ 13.060997 ,  67.221    ,  53.32     ],
         [ 13.060997 ,  67.221    ,  53.32     ],
         [ 13.060997 ,  67.221    ,  53.32     ],
         ...,
         [-62.939003 , -33.779    , -51.68     ],
         [-32.939003 ,  -5.7789993, -23.68     ],
         [-15.939003 ,   8.221001 ,  -6.6800003]],

        [[ 13.060997 ,  67.221    ,  53.32     ],
         [ 13.060997 ,  67.221    ,  53.32     ],
         [ 13.060997 ,  67.221    ,  53.32     ],
         ...,
         [-62.939003 , -33.779    , -51.68     ],
         [-32.939003 ,  -5.7789993, -23.68     ],
         [-15.939003 ,   8.221001 ,  -6.6800003]],

        [[ 11.060997 ,  65.221    ,  51.32     ],
         [ 10.060997 ,  65.221    ,  51.32     ],
         [ 11.060997 ,  65.221    ,  51.32     ],
         ...,
         [-39.939003 ,  -9.778999 , -27.68     ],
         [-13.939003 ,  14.221001 ,  -0.6800003],
         [  4.060997 ,  28.221    ,  13.32     ]],

        ...,

        [[-68.939    ,  35.221    ,   

In [10]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Predicted: [('n02124075', 'Egyptian_cat', np.float32(0.25862992)), ('n02109961', 'Eskimo_dog', np.float32(0.14535175)), ('n02326432', 'hare', np.float32(0.10595597))]


# Car image

In [11]:
img_path = '/content/car.jfif'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [12]:
x

array([[[[-102.939   , -115.779   , -122.68    ],
         [-102.939   , -115.779   , -122.68    ],
         [-102.939   , -115.779   , -122.68    ],
         ...,
         [ -94.939   , -107.779   , -114.68    ],
         [ -93.939   , -106.779   , -113.68    ],
         [ -97.939   , -109.779   , -118.68    ]],

        [[-102.939   , -115.779   , -122.68    ],
         [-102.939   , -115.779   , -122.68    ],
         [-102.939   , -115.779   , -122.68    ],
         ...,
         [ -93.939   , -106.779   , -113.68    ],
         [ -93.939   , -106.779   , -113.68    ],
         [ -80.939   ,  -92.779   , -101.68    ]],

        [[-102.939   , -115.779   , -122.68    ],
         [-102.939   , -115.779   , -122.68    ],
         [-102.939   , -115.779   , -122.68    ],
         ...,
         [ -72.939   ,  -85.779   ,  -92.68    ],
         [ -76.939   ,  -89.779   ,  -96.68    ],
         [ -96.939   , -106.779   , -115.68    ]],

        ...,

        [[ -65.939   ,  -57.779   ,  -

In [13]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
Predicted: [('n03100240', 'convertible', np.float32(0.8605753)), ('n04037443', 'racer', np.float32(0.03948824)), ('n04285008', 'sports_car', np.float32(0.025928108))]
